/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.GetStatus200ResponseAnnouncementsInner;
import de.elbosso.spacetraders.client.model.GetStatus200ResponseLeaderboards;
import de.elbosso.spacetraders.client.model.GetStatus200ResponseLinksInner;
import de.elbosso.spacetraders.client.model.GetStatus200ResponseServerResets;
import de.elbosso.spacetraders.client.model.GetStatus200ResponseStats;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GetStatus200Response
 */
public class GetStatus200ResponseTest {
    private final GetStatus200Response model = new GetStatus200Response();

    /**
     * Model tests for GetStatus200Response
     */
    @Test
    public void testGetStatus200Response() {
        // TODO: test GetStatus200Response
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'resetDate'
     */
    @Test
    public void resetDateTest() {
        // TODO: test resetDate
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'stats'
     */
    @Test
    public void statsTest() {
        // TODO: test stats
    }

    /**
     * Test the property 'leaderboards'
     */
    @Test
    public void leaderboardsTest() {
        // TODO: test leaderboards
    }

    /**
     * Test the property 'serverResets'
     */
    @Test
    public void serverResetsTest() {
        // TODO: test serverResets
    }

    /**
     * Test the property 'announcements'
     */
    @Test
    public void announcementsTest() {
        // TODO: test announcements
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
