/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.api;

import de.elbosso.spacetraders.client.invoker.ApiException;
import de.elbosso.spacetraders.client.model.GetFaction200Response;
import de.elbosso.spacetraders.client.model.GetFactions200Response;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FactionsApi
 */
@Ignore
public class FactionsApiTest {

    private final FactionsApi api = new FactionsApi();

    
    /**
     * Get Faction
     *
     * View the details of a faction.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFactionTest()  throws ApiException
    {
        String factionSymbol = null;
        GetFaction200Response response = api.getFaction(factionSymbol);

        // TODO: test validations
    }
    
    /**
     * List Factions
     *
     * List all discovered factions in the game.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFactionsTest()  throws ApiException{
        Integer page = null;
        Integer limit = null;
        GetFactions200Response response = api.getFactions(page, limit);

        // TODO: test validations
    }
    
}
