/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.Cooldown;
import de.elbosso.spacetraders.client.model.Survey;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateSurvey201ResponseData
 */
@JsonPropertyOrder({
  CreateSurvey201ResponseData.JSON_PROPERTY_COOLDOWN,
  CreateSurvey201ResponseData.JSON_PROPERTY_SURVEYS
})
@JsonTypeName("create_survey_201_response_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-05T09:25:51.979579Z[Etc/UTC]")
public class CreateSurvey201ResponseData {
  public static final String JSON_PROPERTY_COOLDOWN = "cooldown";
  private Cooldown cooldown;

  public static final String JSON_PROPERTY_SURVEYS = "surveys";
  private List<Survey> surveys = new ArrayList<>();

  public CreateSurvey201ResponseData() {
  }

  public CreateSurvey201ResponseData cooldown(Cooldown cooldown) {
    
    this.cooldown = cooldown;
    return this;
  }

   /**
   * Get cooldown
   * @return cooldown
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COOLDOWN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Cooldown getCooldown() {
    return cooldown;
  }


  @JsonProperty(JSON_PROPERTY_COOLDOWN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCooldown(Cooldown cooldown) {
    this.cooldown = cooldown;
  }


  public CreateSurvey201ResponseData surveys(List<Survey> surveys) {
    
    this.surveys = surveys;
    return this;
  }

  public CreateSurvey201ResponseData addSurveysItem(Survey surveysItem) {
    if (this.surveys == null) {
      this.surveys = new ArrayList<>();
    }
    this.surveys.add(surveysItem);
    return this;
  }

   /**
   * Get surveys
   * @return surveys
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SURVEYS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Survey> getSurveys() {
    return surveys;
  }


  @JsonProperty(JSON_PROPERTY_SURVEYS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSurveys(List<Survey> surveys) {
    this.surveys = surveys;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSurvey201ResponseData createSurvey201ResponseData = (CreateSurvey201ResponseData) o;
    return Objects.equals(this.cooldown, createSurvey201ResponseData.cooldown) &&
        Objects.equals(this.surveys, createSurvey201ResponseData.surveys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cooldown, surveys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSurvey201ResponseData {\n");
    sb.append("    cooldown: ").append(toIndentedString(cooldown)).append("\n");
    sb.append("    surveys: ").append(toIndentedString(surveys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

