/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.ExtractionYield;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  Extraction.JSON_PROPERTY_SHIP_SYMBOL,
  Extraction.JSON_PROPERTY_YIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-05T09:25:51.979579Z[Etc/UTC]")
public class Extraction {
  public static final String JSON_PROPERTY_SHIP_SYMBOL = "shipSymbol";
  private String shipSymbol;

  public static final String JSON_PROPERTY_YIELD = "yield";
  private ExtractionYield yield;

  public Extraction() {
  }

  public Extraction shipSymbol(String shipSymbol) {
    
    this.shipSymbol = shipSymbol;
    return this;
  }

   /**
   * Get shipSymbol
   * @return shipSymbol
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHIP_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getShipSymbol() {
    return shipSymbol;
  }


  @JsonProperty(JSON_PROPERTY_SHIP_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShipSymbol(String shipSymbol) {
    this.shipSymbol = shipSymbol;
  }


  public Extraction yield(ExtractionYield yield) {
    
    this.yield = yield;
    return this;
  }

   /**
   * Get yield
   * @return yield
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_YIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ExtractionYield getYield() {
    return yield;
  }


  @JsonProperty(JSON_PROPERTY_YIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setYield(ExtractionYield yield) {
    this.yield = yield;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Extraction extraction = (Extraction) o;
    return Objects.equals(this.shipSymbol, extraction.shipSymbol) &&
        Objects.equals(this.yield, extraction.yield);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipSymbol, yield);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Extraction {\n");
    sb.append("    shipSymbol: ").append(toIndentedString(shipSymbol)).append("\n");
    sb.append("    yield: ").append(toIndentedString(yield)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

