/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.Cooldown;
import de.elbosso.spacetraders.client.model.ShipNav;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * JumpShip200ResponseData
 */
@JsonPropertyOrder({
  JumpShip200ResponseData.JSON_PROPERTY_COOLDOWN,
  JumpShip200ResponseData.JSON_PROPERTY_NAV
})
@JsonTypeName("jump_ship_200_response_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-05T09:25:51.979579Z[Etc/UTC]")
public class JumpShip200ResponseData {
  public static final String JSON_PROPERTY_COOLDOWN = "cooldown";
  private Cooldown cooldown;

  public static final String JSON_PROPERTY_NAV = "nav";
  private ShipNav nav;

  public JumpShip200ResponseData() {
  }

  public JumpShip200ResponseData cooldown(Cooldown cooldown) {
    
    this.cooldown = cooldown;
    return this;
  }

   /**
   * Get cooldown
   * @return cooldown
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COOLDOWN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Cooldown getCooldown() {
    return cooldown;
  }


  @JsonProperty(JSON_PROPERTY_COOLDOWN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCooldown(Cooldown cooldown) {
    this.cooldown = cooldown;
  }


  public JumpShip200ResponseData nav(ShipNav nav) {
    
    this.nav = nav;
    return this;
  }

   /**
   * Get nav
   * @return nav
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShipNav getNav() {
    return nav;
  }


  @JsonProperty(JSON_PROPERTY_NAV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNav(ShipNav nav) {
    this.nav = nav;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JumpShip200ResponseData jumpShip200ResponseData = (JumpShip200ResponseData) o;
    return Objects.equals(this.cooldown, jumpShip200ResponseData.cooldown) &&
        Objects.equals(this.nav, jumpShip200ResponseData.nav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cooldown, nav);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JumpShip200ResponseData {\n");
    sb.append("    cooldown: ").append(toIndentedString(cooldown)).append("\n");
    sb.append("    nav: ").append(toIndentedString(nav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

