/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.Agent;
import de.elbosso.spacetraders.client.model.Ship;
import de.elbosso.spacetraders.client.model.ShipyardTransaction;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PurchaseShip201ResponseData
 */
@JsonPropertyOrder({
  PurchaseShip201ResponseData.JSON_PROPERTY_AGENT,
  PurchaseShip201ResponseData.JSON_PROPERTY_SHIP,
  PurchaseShip201ResponseData.JSON_PROPERTY_TRANSACTION
})
@JsonTypeName("purchase_ship_201_response_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-05T09:25:51.979579Z[Etc/UTC]")
public class PurchaseShip201ResponseData {
  public static final String JSON_PROPERTY_AGENT = "agent";
  private Agent agent;

  public static final String JSON_PROPERTY_SHIP = "ship";
  private Ship ship;

  public static final String JSON_PROPERTY_TRANSACTION = "transaction";
  private ShipyardTransaction transaction;

  public PurchaseShip201ResponseData() {
  }

  public PurchaseShip201ResponseData agent(Agent agent) {
    
    this.agent = agent;
    return this;
  }

   /**
   * Get agent
   * @return agent
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AGENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Agent getAgent() {
    return agent;
  }


  @JsonProperty(JSON_PROPERTY_AGENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgent(Agent agent) {
    this.agent = agent;
  }


  public PurchaseShip201ResponseData ship(Ship ship) {
    
    this.ship = ship;
    return this;
  }

   /**
   * Get ship
   * @return ship
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHIP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Ship getShip() {
    return ship;
  }


  @JsonProperty(JSON_PROPERTY_SHIP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShip(Ship ship) {
    this.ship = ship;
  }


  public PurchaseShip201ResponseData transaction(ShipyardTransaction transaction) {
    
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ShipyardTransaction getTransaction() {
    return transaction;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransaction(ShipyardTransaction transaction) {
    this.transaction = transaction;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseShip201ResponseData purchaseShip201ResponseData = (PurchaseShip201ResponseData) o;
    return Objects.equals(this.agent, purchaseShip201ResponseData.agent) &&
        Objects.equals(this.ship, purchaseShip201ResponseData.ship) &&
        Objects.equals(this.transaction, purchaseShip201ResponseData.transaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agent, ship, transaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseShip201ResponseData {\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    ship: ").append(toIndentedString(ship)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

