/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.Agent;
import de.elbosso.spacetraders.client.model.MarketTransaction;
import de.elbosso.spacetraders.client.model.ShipCargo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SellCargo201ResponseData
 */
@JsonPropertyOrder({
  SellCargo201ResponseData.JSON_PROPERTY_AGENT,
  SellCargo201ResponseData.JSON_PROPERTY_CARGO,
  SellCargo201ResponseData.JSON_PROPERTY_TRANSACTION
})
@JsonTypeName("Sell_Cargo_201_Response_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-05T09:25:51.979579Z[Etc/UTC]")
public class SellCargo201ResponseData {
  public static final String JSON_PROPERTY_AGENT = "agent";
  private Agent agent;

  public static final String JSON_PROPERTY_CARGO = "cargo";
  private ShipCargo cargo;

  public static final String JSON_PROPERTY_TRANSACTION = "transaction";
  private MarketTransaction transaction;

  public SellCargo201ResponseData() {
  }

  public SellCargo201ResponseData agent(Agent agent) {
    
    this.agent = agent;
    return this;
  }

   /**
   * Get agent
   * @return agent
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AGENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Agent getAgent() {
    return agent;
  }


  @JsonProperty(JSON_PROPERTY_AGENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgent(Agent agent) {
    this.agent = agent;
  }


  public SellCargo201ResponseData cargo(ShipCargo cargo) {
    
    this.cargo = cargo;
    return this;
  }

   /**
   * Get cargo
   * @return cargo
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CARGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ShipCargo getCargo() {
    return cargo;
  }


  @JsonProperty(JSON_PROPERTY_CARGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCargo(ShipCargo cargo) {
    this.cargo = cargo;
  }


  public SellCargo201ResponseData transaction(MarketTransaction transaction) {
    
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MarketTransaction getTransaction() {
    return transaction;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransaction(MarketTransaction transaction) {
    this.transaction = transaction;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SellCargo201ResponseData sellCargo201ResponseData = (SellCargo201ResponseData) o;
    return Objects.equals(this.agent, sellCargo201ResponseData.agent) &&
        Objects.equals(this.cargo, sellCargo201ResponseData.cargo) &&
        Objects.equals(this.transaction, sellCargo201ResponseData.transaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agent, cargo, transaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SellCargo201ResponseData {\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

