/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.ShipRequirements;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A module can be installed in a ship and provides a set of capabilities such as storage space or quarters for crew. Module installations are permanent.
 */
@JsonPropertyOrder({
  ShipModule.JSON_PROPERTY_SYMBOL,
  ShipModule.JSON_PROPERTY_CAPACITY,
  ShipModule.JSON_PROPERTY_RANGE,
  ShipModule.JSON_PROPERTY_NAME,
  ShipModule.JSON_PROPERTY_DESCRIPTION,
  ShipModule.JSON_PROPERTY_REQUIREMENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-05T09:25:51.979579Z[Etc/UTC]")
public class ShipModule {
  /**
   * Gets or Sets symbol
   */
  public enum SymbolEnum {
    MINERAL_PROCESSOR_I("MODULE_MINERAL_PROCESSOR_I"),
    
    CARGO_HOLD_I("MODULE_CARGO_HOLD_I"),
    
    CREW_QUARTERS_I("MODULE_CREW_QUARTERS_I"),
    
    ENVOY_QUARTERS_I("MODULE_ENVOY_QUARTERS_I"),
    
    PASSENGER_CABIN_I("MODULE_PASSENGER_CABIN_I"),
    
    MICRO_REFINERY_I("MODULE_MICRO_REFINERY_I"),
    
    ORE_REFINERY_I("MODULE_ORE_REFINERY_I"),
    
    FUEL_REFINERY_I("MODULE_FUEL_REFINERY_I"),
    
    SCIENCE_LAB_I("MODULE_SCIENCE_LAB_I"),
    
    JUMP_DRIVE_I("MODULE_JUMP_DRIVE_I"),
    
    JUMP_DRIVE_II("MODULE_JUMP_DRIVE_II"),
    
    JUMP_DRIVE_III("MODULE_JUMP_DRIVE_III"),
    
    WARP_DRIVE_I("MODULE_WARP_DRIVE_I"),
    
    WARP_DRIVE_II("MODULE_WARP_DRIVE_II"),
    
    WARP_DRIVE_III("MODULE_WARP_DRIVE_III"),
    
    SHIELD_GENERATOR_I("MODULE_SHIELD_GENERATOR_I"),
    
    SHIELD_GENERATOR_II("MODULE_SHIELD_GENERATOR_II");

    private String value;

    SymbolEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SymbolEnum fromValue(String value) {
      for (SymbolEnum b : SymbolEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private SymbolEnum symbol;

  public static final String JSON_PROPERTY_CAPACITY = "capacity";
  private Integer capacity;

  public static final String JSON_PROPERTY_RANGE = "range";
  private Integer range;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_REQUIREMENTS = "requirements";
  private ShipRequirements requirements;

  public ShipModule() {
  }

  public ShipModule symbol(SymbolEnum symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SymbolEnum getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSymbol(SymbolEnum symbol) {
    this.symbol = symbol;
  }


  public ShipModule capacity(Integer capacity) {
    
    this.capacity = capacity;
    return this;
  }

   /**
   * Get capacity
   * minimum: 0
   * @return capacity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCapacity() {
    return capacity;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacity(Integer capacity) {
    this.capacity = capacity;
  }


  public ShipModule range(Integer range) {
    
    this.range = range;
    return this;
  }

   /**
   * Get range
   * minimum: 0
   * @return range
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRange() {
    return range;
  }


  @JsonProperty(JSON_PROPERTY_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRange(Integer range) {
    this.range = range;
  }


  public ShipModule name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public ShipModule description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ShipModule requirements(ShipRequirements requirements) {
    
    this.requirements = requirements;
    return this;
  }

   /**
   * Get requirements
   * @return requirements
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ShipRequirements getRequirements() {
    return requirements;
  }


  @JsonProperty(JSON_PROPERTY_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequirements(ShipRequirements requirements) {
    this.requirements = requirements;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipModule shipModule = (ShipModule) o;
    return Objects.equals(this.symbol, shipModule.symbol) &&
        Objects.equals(this.capacity, shipModule.capacity) &&
        Objects.equals(this.range, shipModule.range) &&
        Objects.equals(this.name, shipModule.name) &&
        Objects.equals(this.description, shipModule.description) &&
        Objects.equals(this.requirements, shipModule.requirements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, capacity, range, name, description, requirements);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipModule {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

