/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * 
 */
public enum ShipType {
  
  PROBE("SHIP_PROBE"),
  
  MINING_DRONE("SHIP_MINING_DRONE"),
  
  INTERCEPTOR("SHIP_INTERCEPTOR"),
  
  LIGHT_HAULER("SHIP_LIGHT_HAULER"),
  
  COMMAND_FRIGATE("SHIP_COMMAND_FRIGATE"),
  
  EXPLORER("SHIP_EXPLORER"),
  
  HEAVY_FREIGHTER("SHIP_HEAVY_FREIGHTER"),
  
  LIGHT_SHUTTLE("SHIP_LIGHT_SHUTTLE"),
  
  ORE_HOUND("SHIP_ORE_HOUND"),
  
  REFINING_FREIGHTER("SHIP_REFINING_FREIGHTER");

  private String value;

  ShipType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ShipType fromValue(String value) {
    for (ShipType b : ShipType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

