/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.Cooldown;
import de.elbosso.spacetraders.client.model.ShipCargo;
import de.elbosso.spacetraders.client.model.ShipRefine200ResponseDataProducedInner;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ShipRefine200ResponseData
 */
@JsonPropertyOrder({
  ShipRefine200ResponseData.JSON_PROPERTY_CARGO,
  ShipRefine200ResponseData.JSON_PROPERTY_COOLDOWN,
  ShipRefine200ResponseData.JSON_PROPERTY_PRODUCED,
  ShipRefine200ResponseData.JSON_PROPERTY_CONSUMED
})
@JsonTypeName("Ship_Refine_200_Response_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-05T09:25:51.979579Z[Etc/UTC]")
public class ShipRefine200ResponseData {
  public static final String JSON_PROPERTY_CARGO = "cargo";
  private ShipCargo cargo;

  public static final String JSON_PROPERTY_COOLDOWN = "cooldown";
  private Cooldown cooldown;

  public static final String JSON_PROPERTY_PRODUCED = "produced";
  private List<ShipRefine200ResponseDataProducedInner> produced = new ArrayList<>();

  public static final String JSON_PROPERTY_CONSUMED = "consumed";
  private List<ShipRefine200ResponseDataProducedInner> consumed = new ArrayList<>();

  public ShipRefine200ResponseData() {
  }

  public ShipRefine200ResponseData cargo(ShipCargo cargo) {
    
    this.cargo = cargo;
    return this;
  }

   /**
   * Get cargo
   * @return cargo
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CARGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ShipCargo getCargo() {
    return cargo;
  }


  @JsonProperty(JSON_PROPERTY_CARGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCargo(ShipCargo cargo) {
    this.cargo = cargo;
  }


  public ShipRefine200ResponseData cooldown(Cooldown cooldown) {
    
    this.cooldown = cooldown;
    return this;
  }

   /**
   * Get cooldown
   * @return cooldown
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COOLDOWN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Cooldown getCooldown() {
    return cooldown;
  }


  @JsonProperty(JSON_PROPERTY_COOLDOWN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCooldown(Cooldown cooldown) {
    this.cooldown = cooldown;
  }


  public ShipRefine200ResponseData produced(List<ShipRefine200ResponseDataProducedInner> produced) {
    
    this.produced = produced;
    return this;
  }

  public ShipRefine200ResponseData addProducedItem(ShipRefine200ResponseDataProducedInner producedItem) {
    if (this.produced == null) {
      this.produced = new ArrayList<>();
    }
    this.produced.add(producedItem);
    return this;
  }

   /**
   * Get produced
   * @return produced
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRODUCED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ShipRefine200ResponseDataProducedInner> getProduced() {
    return produced;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProduced(List<ShipRefine200ResponseDataProducedInner> produced) {
    this.produced = produced;
  }


  public ShipRefine200ResponseData consumed(List<ShipRefine200ResponseDataProducedInner> consumed) {
    
    this.consumed = consumed;
    return this;
  }

  public ShipRefine200ResponseData addConsumedItem(ShipRefine200ResponseDataProducedInner consumedItem) {
    if (this.consumed == null) {
      this.consumed = new ArrayList<>();
    }
    this.consumed.add(consumedItem);
    return this;
  }

   /**
   * Get consumed
   * @return consumed
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONSUMED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ShipRefine200ResponseDataProducedInner> getConsumed() {
    return consumed;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsumed(List<ShipRefine200ResponseDataProducedInner> consumed) {
    this.consumed = consumed;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipRefine200ResponseData shipRefine200ResponseData = (ShipRefine200ResponseData) o;
    return Objects.equals(this.cargo, shipRefine200ResponseData.cargo) &&
        Objects.equals(this.cooldown, shipRefine200ResponseData.cooldown) &&
        Objects.equals(this.produced, shipRefine200ResponseData.produced) &&
        Objects.equals(this.consumed, shipRefine200ResponseData.consumed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cargo, cooldown, produced, consumed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipRefine200ResponseData {\n");
    sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
    sb.append("    cooldown: ").append(toIndentedString(cooldown)).append("\n");
    sb.append("    produced: ").append(toIndentedString(produced)).append("\n");
    sb.append("    consumed: ").append(toIndentedString(consumed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

