/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.elbosso.spacetraders.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.elbosso.spacetraders.client.model.ShipFuelConsumed;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Details of the ship&#39;s fuel tanks including how much fuel was consumed during the last transit or action.
 */
@JsonPropertyOrder({
  ShipFuel.JSON_PROPERTY_CURRENT,
  ShipFuel.JSON_PROPERTY_CAPACITY,
  ShipFuel.JSON_PROPERTY_CONSUMED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-05T09:25:51.979579Z[Etc/UTC]")
public class ShipFuel {
  public static final String JSON_PROPERTY_CURRENT = "current";
  private Integer current;

  public static final String JSON_PROPERTY_CAPACITY = "capacity";
  private Integer capacity;

  public static final String JSON_PROPERTY_CONSUMED = "consumed";
  private ShipFuelConsumed consumed;

  public ShipFuel() {
  }

  public ShipFuel current(Integer current) {
    
    this.current = current;
    return this;
  }

   /**
   * The current amount of fuel in the ship&#39;s tanks.
   * minimum: 0
   * @return current
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCurrent() {
    return current;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrent(Integer current) {
    this.current = current;
  }


  public ShipFuel capacity(Integer capacity) {
    
    this.capacity = capacity;
    return this;
  }

   /**
   * The maximum amount of fuel the ship&#39;s tanks can hold.
   * minimum: 0
   * @return capacity
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCapacity() {
    return capacity;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCapacity(Integer capacity) {
    this.capacity = capacity;
  }


  public ShipFuel consumed(ShipFuelConsumed consumed) {
    
    this.consumed = consumed;
    return this;
  }

   /**
   * Get consumed
   * @return consumed
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONSUMED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShipFuelConsumed getConsumed() {
    return consumed;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConsumed(ShipFuelConsumed consumed) {
    this.consumed = consumed;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipFuel shipFuel = (ShipFuel) o;
    return Objects.equals(this.current, shipFuel.current) &&
        Objects.equals(this.capacity, shipFuel.capacity) &&
        Objects.equals(this.consumed, shipFuel.consumed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(current, capacity, consumed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipFuel {\n");
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    consumed: ").append(toIndentedString(consumed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

